## Lab 1 - Number estimation (free exploration) - ST134605 AND AJ

For this lab, please work in pairs. The required Python packages have been imported for you below.

In [3]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

The target number (i.e. ground truth) for each experimental trial is provided in the following python array.

In [4]:
targets = np.array([3, 8, 40, 2, 5, 30, 7, 35, 6, 15, 10, 20, 9, 25, 4]);

Read in the experimental data collected in-class. `df` is a dataframe of size _(Participants x Trials)_.

In [5]:
df = pd.read_csv('data-number-estimation.csv')

Display the content of the data frame.

In [6]:
df

,Trial 1,Trial 2,Trial 3,Trial 4,Trial 5,Trial 6,Trial 7,Trial 8,Trial 9,Trial 10,Trial 11,Trial 12,Trial 13,Trial 14,Trial 15
0,3,8,27,2,5,25,8,30,6,20,17,25,8,26,4
1,3,8,24,2,5,25,7,25,6,26,12,35,12,30,4
2,3,8,30,2,5,40,7,30,6,20,9,20,9,35,4
3,3,8,30,2,5,25,7,25,6,15,9,20,9,25,4
4,3,9,27,2,5,24,7,35,6,15,10,25,9,23,4
5,3,9,36,2,6,38,8,32,6,15,20,28,15,23,4
6,3,7,25,1,5,25,7,30,6,17,11,23,10,36,4
7,3,8,30,2,6,30,8,30,7,15,10,20,9,30,4
8,3,8,30,2,5,25,6,40,6,20,11,30,9,30,4
9,3,8,25,2,5,30,7,27,6,15,10,20,9,20,4
10,3,8,26,2,5,19,7,30,6,16,10,21,9,32,4
11,3,8,22,2,5,26,7,25,6,12,9,18,9,23,4
12,3,8,20,2,5,20,7,25,6,12,10,18,12,14,4
13,3,9,32,2,5,27,9,38,6,16,11,34,17,28,4
14,3,9,40,2,5,50,7,40,8,20,11,24,10,30,4
15,3,8,39,2,5,40,7,40,6,13,10,15,9,38,4
16,3,7,23,2,5,26,7,25,6,18,10,20,9,21,4
17,3,8,50,2,5,30,6,30,6,15,10,20,9,25,4
18,3,8,25,2,5,30,7,35,6,15,11,25,9,26,4
19,3,9,20,2,6,20,7,30,6,15,12,18,9,20,4
20,3,7,25,2,4,20,7,30,6,15,10,25,9,15,4
21,3,8,23,2,5,25,7,29,6,15,11,18,9,22,4
22,3,8,40,2,5,20,7,25,6,18,8,15,12,25,4
23,3,9,27,2,5,38,7,38,6,17,10,29,10,32,4
24,3,8,31,2,5,25,7,50,6,19,10,20,9,23,4
25,3,8,27,2,5,25,7,22,6,18,10,23,9,20,4
26,3,7,35,2,5,20,7,25,6,17,10,18,9,20,4
27,3,10,30,2,6,27,8,23,6,14,8,19,7,29,3
28,3,8,27,2,5,21,7,29,6,18,10,27,9,24,4
29,3,10,8,2,5,25,8,30,6,17,12,18,10,21,4
30,3,8,35,2,5,30,7,35,6,13,9,20,10,20,5
31,3,9,40,2,5,30,7,30,6,20,13,25,10,35,4
32,3,9,30,2,5,40,10,35,6,15,10,20,10,30,4
33,3,10,30,2,5,25,7,28,6,18,15,28,10,28,4
34,3,8,47,2,5,26,7,45,6,14,10,22,9,23,4
35,3,8,20,2,5,15,9,18,6,15,10,20,9,18,4
36,3,7,21,2,5,25,7,19,6,17,9,18,7,23,4
37,3,8,27,2,5,25,8,30,7,15,11,17,9,28,4
38,3,8,30,2,5,35,7,45,6,16,9,19,9,23,4
39,3,8,21,2,5,27,7,26,6,14,11,16,9,21,4
40,3,8,20,2,5,20,7,31,6,19,12,16,16,27,4
41,3,8,20,2,5,25,7,28,6,18,10,20,9,19,4
42,3,15,50,2,6,50,8,60,7,20,10,30,10,40,4
43,3,8,45,2,5,46,6,40,6,18,9,20,9,23,4
44,3,9,19,2,5,20,7,25,6,14,11,18,9,23,4
45,3,7,25,2,5,25,8,25,6,15,12,18,11,15,4
46,3,7,23,2,5,18,6,20,5,13,9,12,8,21,4

Get a column from the data frame.

In [7]:
df['Trial 1']

0     3
1     3
2     3
3     3
4     3
5     3
6     3
7     3
8     3
9     3
10    3
11    3
12    3
13    3
14    3
15    3
16    3
17    3
18    3
19    3
20    3
21    3
22    3
23    3
24    3
25    3
26    3
27    3
28    3
29    3
30    3
31    3
32    3
33    3
34    3
35    3
36    3
37    3
38    3
39    3
40    3
41    3
42    3
43    3
44    3
45    3
46    3
Name: Trial 1, dtype: int64

Get multiple columns.

In [8]:
df[['Trial 6','Trial 10']]

    Trial 6  Trial 10
0        25        20
1        25        26
2        40        20
3        25        15
4        24        15
5        38        15
6        25        17
7        30        15
8        25        20
9        30        15
10       19        16
11       26        12
12       20        12
13       27        16
14       50        20
15       40        13
16       26        18
17       30        15
18       30        15
19       20        15
20       20        15
21       25        15
22       20        18
23       38        17
24       25        19
25       25        18
26       20        17
27       27        14
28       21        18
29       25        17
30       30        13
31       30        20
32       40        15
33       25        18
34       26        14
35       15        15
36       25        17
37       25        15
38       35        16
39       27        14
40       20        19
41       25        18
42       50        20
43       46        18
44       20        14
45       25        15
46       18        13

Convert a data frame column into an array.

In [9]:
trl1 = np.asarray(df['Trial 1'])

View the array.

In [10]:
trl1

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3])

Check the length of the array.

In [11]:
len(trl1)

47

To obtain credits for this assignment, submit through Quercus 1) a ~2-page PDF write-up addressing the points below (which can be an export of your Python notebook that includes all of your solutions), and 2) the executable Python notebook file that you have written:

* State your hypothesis in 1-2 sentences, and your rationale or scientific basis of the proposed hypothesis. **[2pts]**
* Generate one figure or table (appropriately annotated) from the data provided that helps to evaluate or illustrate the validity of your hypothesis. **[2pts]**
* Summarize the results and your observations, and suggest limitations of your approach or the experiment. **[2pts]**
* Outline a plan to extend your findings and state your conclusion in 1 sentence. **[2pts]**
* Submit your Python Jupyter notebook that reproduces all the findings reported (in a separate file). **[2pts]**

In [40]:
trl1s = sum(trl1)/47

In [41]:
trl2 = np.asarray(df['Trial 2'])
trl2s = sum(trl2)/47

In [42]:
trl3 = np.asarray(df['Trial 3'])
trl3s = sum(trl3)/47

In [43]:
trl4 = np.asarray(df['Trial 4'])
trl4s = sum(trl4)/47

In [44]:
trl5 = np.asarray(df['Trial 5'])
trl5s = sum(trl5)/47

In [45]:
trl6 = np.asarray(df['Trial 6'])
trl6s = sum(trl6)/47

In [46]:
trl7 = np.asarray(df['Trial 7'])
trl7s = sum(trl7)/47

In [47]:
trl8 = np.asarray(df['Trial 8'])
trl8s = sum(trl8)/47

In [48]:
trl9 = np.asarray(df['Trial 9'])
trl9s = sum(trl9)/47

In [49]:
trl10 = np.asarray(df['Trial 10'])
trl10s = sum(trl10)/47

In [50]:
trl11 = np.asarray(df['Trial 11'])
trl11s = sum(trl11)/47

In [51]:
trl12 = np.asarray(df['Trial 12'])
trl12s = sum(trl12)/47

In [52]:
trl13 = np.asarray(df['Trial 13'])
trl13s = sum(trl13)/47

In [53]:
trl14 = np.asarray(df['Trial 14'])
trl14s = sum(trl14)/47

In [54]:
trl15 = np.asarray(df['Trial 15'])
trl15s = sum(trl15)/47

In [55]:
averages = [trl1s, trl2s, trl3s, trl4s, trl5s, trl6s, trl7s, trl8s, trl9s, trl10s, trl11s, trl12s, trl13s, trl14s, trl15s]

In [59]:
averages

[3.0,
 8.319148936170214,
 28.872340425531913,
 1.9787234042553192,
 5.085106382978723,
 27.72340425531915,
 7.23404255319149,
 31.127659574468087,
 6.085106382978723,
 16.425531914893618,
 10.680851063829786,
 21.48936170212766,
 9.74468085106383,
 25.170212765957448,
 4.0]

In [64]:
data = []
x = 0
y = 0
z = 0
d = 0
error = 0
for item in targets:
    y = item
    z = round(averages[x], 2)
    d = round(z - y, 2)
    error = round((d/y)*100, 2)
    data.append([y, z, d, error])
    x += 1

In [65]:
pd.DataFrame(data, columns=["Target", "Average", "Variance", "Error Percentage (%)"])

    Target  Average  Variance  Error Percentage (%)
0        3     3.00      0.00                  0.00
1        8     8.32      0.32                  4.00
2       40    28.87    -11.13                -27.82
3        2     1.98     -0.02                 -1.00
4        5     5.09      0.09                  1.80
5       30    27.72     -2.28                 -7.60
6        7     7.23      0.23                  3.29
7       35    31.13     -3.87                -11.06
8        6     6.09      0.09                  1.50
9       15    16.43      1.43                  9.53
10      10    10.68      0.68                  6.80
11      20    21.49      1.49                  7.45
12       9     9.74      0.74                  8.22
13      25    25.17      0.17                  0.68
14       4     4.00      0.00                  0.00